/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#222a3d",
        "secondary-fixed": "#acedff",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed-dim": "#4cd7f6",
        "secondary": "#4cd7f6",
        "on-background": "#dae2fd",
        "background": "#0b1326",
        "tertiary-fixed": "#ffd6fd",
        "surface-container-lowest": "#060e20",
        "surface-container": "#171f33",
        "surface": "#0b1326",
        "tertiary-container": "#a500bd",
        "on-secondary-container": "#00424e",
        "on-primary": "#1d00a5",
        "on-surface-variant": "#c7c4d8",
        "on-tertiary": "#580065",
        "error": "#ffb4ab",
        "surface-bright": "#31394d",
        "tertiary-fixed-dim": "#fbabff",
        "surface-variant": "#2d3449",
        "primary-fixed-dim": "#c3c0ff",
        "outline-variant": "#464555",
        "primary": "#c3c0ff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-low": "#131b2e",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed-variant": "#7c008e",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#dad7ff",
        "on-tertiary-fixed": "#36003e",
        "error-container": "#93000a",
        "on-secondary-fixed": "#001f26",
        "inverse-primary": "#4d44e3",
        "surface-tint": "#c3c0ff",
        "secondary-container": "#03b5d3",
        "primary-fixed": "#e2dfff",
        "on-surface": "#dae2fd",
        "outline": "#918fa1",
        "inverse-on-surface": "#283044",
        "primary-container": "#4f46e5",
        "on-tertiary-container": "#ffcafe",
        "tertiary": "#fbabff",
        "on-error": "#690005",
        "surface-dim": "#0b1326",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary": "#003640",
        "inverse-surface": "#dae2fd"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
    },
  },
  plugins: [],
}

